-- 경기도에 위치한 식품창고 목록 출력하기
SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, IFNULL(FREEZER_YN, 'N')
    FROM FOOD_WAREHOUSE 
    WHERE ADDRESS LIKE '경기도%'
    ORDER BY WAREHOUSE_ID

-- 잡은 물고기의 평균 길이 구하기
SELECT ROUND(AVG(IFNULL(LENGTH, 10)), 2) AS AVERAGE_LENGTH
    FROM FISH_INFO

-- 업그레이드 할 수 없는 아이템 구하기
SELECT ITEM_ID, ITEM_NAME, RARITY
    FROM ITEM_INFO
    WHERE ITEM_ID NOT IN (
        SELECT DISTINCT PARENT_ITEM_ID
        FROM ITEM_TREE
        WHERE PARENT_ITEM_ID IS NOT NULL
    )
    ORDER BY 1 DESC