-- 조건에 맞는 도서와 저자 리스트 출력하기 Lv2
SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
    FROM BOOK 
    JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
    WHERE BOOK.CATEGORY = '경제'
    ORDER BY PUBLISHED_DATE;

-- 상품 별 오프라인 매출 구하기 lV2
SELECT PRODUCT_CODE, SUM(PRICE * SALES_AMOUNT) AS SALES
    FROM PRODUCT
    JOIN OFFLINE_SALE ON PRODUCT.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID
    GROUP BY PRODUCT_CODE
    ORDER BY SALES DESC, PRODUCT_CODE;

-- 없어진 기록 찾기 lV3
SELECT O.ANIMAL_ID, O.NAME
    FROM ANIMAL_INS I
    RIGHT OUTER JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
    WHERE I.ANIMAL_ID IS NULL
    ORDER BY O.ANIMAL_ID;

SELECT ANIMAL_ID, NAME
    FROM ANIMAL_OUTS
    WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_INS)
    ORDER BY ANIMAL_ID;

SELECT ANIMAL_ID, NAME
    FROM ANIMAL_OUTS O
    WHERE NOT EXISTS (SELECT ANIMAL_ID, NAME 
                        FROM ANIMAL_INS I
                        WHERE O.ANIMAL_ID = I.ANIMAL_ID)
    ORDER BY ANIMAL_ID;

-- FrontEnd 개발자 찾기
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
    FROM DEVELOPERS
    WHERE SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY='Front End') > 0
    ORDER BY ID;

-- 오랜 기간 보호한 동물
SELECT I.NAME, I.DATETIME
    FROM ANIMAL_INS I
    LEFT JOIN ANIMAL_OUTS O
    ON I.ANIMAL_ID = O.ANIMAL_ID
    WHERE O.ANIMAL_ID IS NULL
    ORDER BY DATETIME
    LIMIT 3;

-- 5월 식품들의 총매출 조회하기
SELECT P.PRODUCT_ID, PRODUCT_NAME, SUM(AMOUNT*P.PRICE) AS TOTAL_SALES
    FROM FOOD_PRODUCT P
    JOIN FOOD_ORDER O ON P.PRODUCT_ID=O.PRODUCT_ID
    WHERE PRODUCE_DATE LIKE '2022-05%'
    GROUP BY PRODUCT_ID
    ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID ASC;

-- 주문량이 많은 아이스크림들 조회하기
SELECT H.FLAVOR
    FROM FIRST_HALF H
    JOIN JULY J ON H.FLAVOR=J.FLAVOR
    GROUP BY FLAVOR
    ORDER BY SUM(H.TOTAL_ORDER)+SUM(J.TOTAL_ORDER) DESC
    LIMIT 3;