-- 재구매가 일어난 상품과 회원 리스트 구하기 
SELECT USER_ID, PRODUCT_ID
    FROM ONLINE_SALE
    GROUP BY USER_ID, PRODUCT_ID
    HAVING COUNT(*)>=2
    ORDER BY USER_ID ASC, PRODUCT_ID DESC;

-- 업그레이드 된 아이템 구하기
SELECT ITEM_ID, ITEM_NAME, RARITY
    FROM ITEM_INFO
    WHERE ITEM_ID IN (SELECT A.ITEM_ID
                      FROM ITEM_INFO I, ITEM_TREE A
                      WHERE I.ITEM_ID=A.PARENT_ITEM_ID AND RARITY='RARE')
    ORDER BY ITEM_ID DESC;

-- 조건에 맞는 개발자 찾기
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
    FROM DEVELOPERS
    WHERE SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME='Python')
        OR SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME='C#')
    ORDER BY ID;