-- 평균 일일 대여 요금 구하기
 SELECT round(AVG(DAILY_FEE),0) 
    FROM CAR_RENTAL_COMPANY_CAR 
    WHERE CAR_TYPE='SUV';

-- 아픈 동물 찾기
SELECT ANIMAL_ID, NAME
    FROM ANIMAL_INS
    WHERE INTAKE_CONDITION='Sick'
    ORDER BY ANIMAL_ID;

-- 과일로 만든 아이스크림 고르기
SELECT FIRST_HALF.FLAVOR
    FROM FIRST_HALF, ICECREAM_INFO
    WHERE FIRST_HALF.FLAVOR=ICECREAM_INFO.FLAVOR AND FIRST_HALF.TOTAL_ORDER>3000 AND ICECREAM_INFO.INGREDIENT_TYPE='fruit_based'
    ORDER BY TOTAL_ORDER DESC;

-- 흉부외과 또는 일반외과 의사 목록 출력하기
SELECT DR_NAME, DR_ID, MCDP_CD, DATE_FORMAT(HIRE_YMD, '%Y-%m-%d') AS HIRE_YMD
    FROM DOCTOR
    WHERE MCDP_CD='CS' or MCDP_CD='GS'
    ORDER BY HIRE_YMD DESC, DR_NAME ASC;

-- 조건에 부합하는 중고거래 댓글 조회하기
SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
    FROM USED_GOODS_BOARD AS A
    INNER JOIN USED_GOODS_REPLY AS B ON A.BOARD_ID=B.BOARD_ID
    WHERE SUBSTR(A.CREATED_DATE, 1,7) = '2022-10'
    ORDER BY B.CREATED_DATE, A.TITLE;

-- 12세 이하인 여자 환자 목록 출력하기
SELECT PT_NAME, PT_NO, GEND_CD, AGE, IFNULL(TLNO, 'NONE') AS TLNO
    FROM PATIENT
    WHERE AGE <= 12 AND GEND_CD='W'
    ORDER BY AGE DESC, PT_NAME;

-- 특정 세대의 대장균 찾기
SELECT THREE.ID
    FROM ECOLI_DATA AS ONE
    INNER JOIN ECOLI_DATA AS TWO ON ONE.ID=TWO.PARENT_ID AND ONE.PARENT_ID IS NULL
    INNER JOIN ECOLI_DATA AS THREE ON TWO.ID=THREE.PARENT_ID
    ORDER BY ID;

-- 상위 n개 레코드
SELECT NAME
    FROM ANIMAL_INS
    ORDER BY DATETIME
    LIMIT 1;

-- 특정 형질을 가지는 대장균 찾기
SELECT COUNT(ID) AS COUNT
    FROM ECOLI_DATA
    WHERE (GENOTYPE & 2) != 2
        AND ((GENOTYPE & 4) = 4 OR (GENOTYPE & 1) = 1);