-- 평균 일일 대여 요금 구하기
 SELECT round(AVG(DAILY_FEE),0) 
    FROM CAR_RENTAL_COMPANY_CAR 
    WHERE CAR_TYPE='SUV';

-- 아픈 동물 찾기
SELECT ANIMAL_ID, NAME
    FROM ANIMAL_INS
    WHERE INTAKE_CONDITION='Sick'
    ORDER BY ANIMAL_ID;
