-- 중복 제거하기
SELECT COUNT(DISTINCT NAME)
    FROM ANIMAL_INS
/* WHERE NAME IS NOT NULL 은 없어도 됨
   COUNT(column)은 NULL을 세지 않음 */

-- 연도별 대장균 크기의 편차 구하기
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, 
    (
        SELECT MAX(SIZE_OF_COLONY)
        FROM ECOLI_DATA
        WHERE YEAR(DIFFERENTIATION_DATE) = YEAR
    ) - SIZE_OF_COLONY AS YEAR_DEV, ID
    FROM ECOLI_DATA
    ORDER BY 1, 2

-- 물고기 종류 별 대어 찾기
SELECT ID, FISH_NAME, LENGTH
    FROM FISH_INFO I
    JOIN FISH_NAME_INFO N ON I.FISH_TYPE=N.FISH_TYPE
    WHERE LENGTH = (
        SELECT MAX(LENGTH)
        FROM FISH_INFO
        WHERE FISH_TYPE = I.FISH_TYPE
    )
    ORDER BY 1